version: "3"

services:
  api:
    image: challenge/api
    ports:
      - 9000:9000
    links:
      - mongo

  web:
    image: challenge/web
    ports:
      - 3000:3000
  
  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
  
volumes:
  data:
